# Generated by Django 4.0.5 on 2023-01-22 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreYApellido', models.CharField(max_length=200, verbose_name='Nombre y apellido')),
                ('dni', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('plazas', models.IntegerField()),
                ('esPlantaBaja', models.BooleanField(verbose_name='Planta baja')),
                ('habilitada', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigenciaDesde', models.DateField(verbose_name='Vigencia desde')),
                ('vigenciaHasta', models.DateField(verbose_name='Vigencia hasta')),
                ('idTipoLista', models.CharField(choices=[('TA', 'Temporada Alta'), ('TM', 'Temporada Media'), ('TB', 'Temporada Baja')], max_length=3, verbose_name='Tipo de lista')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaIngreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('fechaEgreso', models.DateField(verbose_name='Fecha de Egreso')),
                ('fechaRegistro', models.DateField(verbose_name='Fecha de registro')),
                ('cantidadPersonas', models.IntegerField(verbose_name='Cantidad de personas')),
                ('seniaSolicitada', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Seña solicitada')),
                ('precioTotal', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Precio total')),
                ('precioPorDia', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por día')),
                ('incluyeDesayuno', models.BooleanField(verbose_name='Desayuno')),
                ('importeDescuento', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Importe de descuento')),
                ('porcentajeDescuento', models.IntegerField(null=True, verbose_name='Porcentaje de descuento')),
                ('descuentoPorPorcentaje', models.BooleanField(null=True, verbose_name='Descuento por porcentaje')),
                ('observaciones', models.TextField(blank=True, max_length=500)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.cliente', verbose_name='Cliente')),
                ('idHabitacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hotel.habitacion', verbose_name='Hab')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTipoMovimiento', models.CharField(choices=[('IN', 'Ingreso'), ('EG', 'Egreso')], max_length=3, verbose_name='Tipo de movimiento')),
                ('idConcepto', models.CharField(choices=[('SEN', 'Seña'), ('SAL', 'Saldo'), ('GVS', 'Gastos varios'), ('LAV', 'Lavadero'), ('PAN', 'Panaderia')], max_length=3, verbose_name='Concepto')),
                ('idFormaPago', models.CharField(choices=[('CRE', 'Credito'), ('DEB', 'Debito'), ('EFE', 'Efectivo'), ('TRA', 'Transferencia')], max_length=3, verbose_name='Forma de pago')),
                ('fecha', models.DateField()),
                ('monto', models.IntegerField()),
                ('numeroComprobante', models.CharField(blank=True, max_length=50, verbose_name='Número de comprobante')),
                ('idReserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hotel.reserva', verbose_name='Reserva')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleListaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadPersonas', models.IntegerField(verbose_name='Cantidad de personas')),
                ('precioPorDia', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por día')),
                ('idListaPrecio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.listaprecio')),
            ],
        ),
    ]
