# Generated by Django 4.0.5 on 2022-07-02 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreYApellido', models.CharField(max_length=200, verbose_name='Nombre y apellido')),
                ('dni', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('esPlantaBaja', models.BooleanField(verbose_name='Planta baja')),
                ('plazas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigenciaDesde', models.DateField()),
                ('vigenciaHasta', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaIngreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('fechaEgreso', models.DateField(verbose_name='Fecha de Egreso')),
                ('cantidadPersonas', models.IntegerField(verbose_name='Cantidad de personas')),
                ('senia', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Seña')),
                ('precioTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precioPorDia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('incluyeDesayuno', models.BooleanField()),
                ('observaciones', models.TextField(blank=True, max_length=500)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.cliente', verbose_name='Cliente')),
                ('idHabitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.habitacion')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTipoMovimiento', models.CharField(choices=[('IN', 'Ingreso'), ('EG', 'Egreso')], max_length=3, verbose_name='Tipo de movimiento')),
                ('idConcepto', models.CharField(choices=[('SEN', 'Seña'), ('SAL', 'Saldo'), ('GVS', 'Gastos varios'), ('LAV', 'Lavadero'), ('PAN', 'Panaderia')], max_length=3)),
                ('idFormaPago', models.CharField(choices=[('CRE', 'Credito'), ('DEB', 'Debito'), ('EFE', 'Efectivo'), ('TRA', 'Transferencia')], max_length=3)),
                ('fecha', models.DateField()),
                ('monto', models.IntegerField()),
                ('numeroComprobante', models.CharField(blank=True, max_length=50)),
                ('idReserva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hotel.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleListaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadPersonas', models.IntegerField()),
                ('precioPorDia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idListaPrecio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.listaprecio')),
            ],
        ),
        migrations.CreateModel(
            name='DescuentoDetalleListaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDescuento', models.CharField(choices=[('CP', '5%'), ('DP', '10%'), ('QP', '15%'), ('VP', '20%')], max_length=3, verbose_name='Porcentaje de descuento')),
                ('precioTotalRedondeado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precioPorDia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidadDias', models.IntegerField()),
                ('idDetalleListaPrecio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.detallelistaprecio')),
            ],
        ),
    ]
