# Generated by Django 4.0.5 on 2023-02-20 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_reserva_fechacancelacion_reserva_motivocancelacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='motivoCancelacion',
        ),
    ]
